services:
#    azovsky_test.example:
#        class: Azovsky\TestBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    utilites:
            class:        Azovsky\TestBundle\Utilites
 